"""remove_deprecated_transaction_fields

Revision ID: 1f70eef705f1
Revises: c254637baa44
Create Date: 2025-11-27 17:26:10.683614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f70eef705f1'
down_revision = 'c254637baa44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'balance_after')
    op.drop_column('transactions', 'price')
    op.drop_column('transactions', 'fee')
    op.drop_column('transactions', 'external_id')
    op.drop_column('transactions', 'is_confirmed')
    op.drop_column('transactions', 'tax')
    op.drop_column('transactions', 'realized_profit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('realized_profit', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('tax', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('is_confirmed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('external_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('fee', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('price', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('balance_after', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
