"""add market column to assets

Revision ID: fceacb9aa017
Revises: d17a07f6daa6
Create Date: 2025-12-16 21:49:39.808098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fceacb9aa017'
down_revision = 'd17a07f6daa6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('market', sa.String(length=20), nullable=True))
    op.drop_index('idx_assets_review_due', table_name='assets', postgresql_where='((is_active = true) AND (next_review_date IS NOT NULL))')
    op.drop_index('idx_transactions_confirmed', table_name='transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_transactions_confirmed', 'transactions', ['confirmed'], unique=False)
    op.create_index('idx_assets_review_due', 'assets', ['user_id', 'next_review_date'], unique=False, postgresql_where='((is_active = true) AND (next_review_date IS NOT NULL))')
    op.drop_column('assets', 'market')
    # ### end Alembic commands ###
