"""add_out_asset_and_in_asset_transaction_types

Revision ID: c1bdd90a015d
Revises: 3c1b2b2c9aa1
Create Date: 2025-12-02 15:47:59.863631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1bdd90a015d'
down_revision = '3c1b2b2c9aa1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the old CHECK constraint
    op.drop_constraint('valid_transaction_type', 'transactions', type_='check')
    
    # Create the new CHECK constraint with out_asset and in_asset
    op.create_check_constraint(
        'valid_transaction_type',
        'transactions',
        "type IN ('buy', 'sell', 'deposit', 'withdraw', 'cash_dividend', 'stock_dividend', 'interest', 'fee', "
        "'transfer_in', 'transfer_out', 'adjustment', 'invest', 'redeem', "
        "'internal_transfer', 'card_payment', 'promotion_deposit', 'auto_transfer', 'remittance', 'exchange', "
        "'out_asset', 'in_asset')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the new CHECK constraint
    op.drop_constraint('valid_transaction_type', 'transactions', type_='check')
    
    # Restore the old CHECK constraint without out_asset and in_asset
    op.create_check_constraint(
        'valid_transaction_type',
        'transactions',
        "type IN ('buy', 'sell', 'deposit', 'withdraw', 'cash_dividend', 'stock_dividend', 'interest', 'fee', "
        "'transfer_in', 'transfer_out', 'adjustment', 'invest', 'redeem', "
        "'internal_transfer', 'card_payment', 'promotion_deposit', 'auto_transfer', 'remittance', 'exchange')"
    )
    # ### end Alembic commands ###
