"""add payment_cancel transaction type

Revision ID: c76e7307e524
Revises: add_savings_deposit
Create Date: 2025-12-07 17:31:25.102438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c76e7307e524'
down_revision = 'add_savings_deposit'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
