"""add flow_type column and maintain confirmed

Revision ID: 244902ea97c9
Revises: 764c6ad75ec2
Create Date: 2025-12-08 23:19:30.511269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '244902ea97c9'
down_revision = '764c6ad75ec2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('price', sa.Numeric(precision=20, scale=6), nullable=True))
    op.add_column('transactions', sa.Column('fee', sa.Numeric(precision=20, scale=6), nullable=True))
    op.add_column('transactions', sa.Column('tax', sa.Numeric(precision=20, scale=6), nullable=True))
    op.add_column('transactions', sa.Column('realized_profit', sa.Numeric(precision=20, scale=6), nullable=True))
    op.add_column('transactions', sa.Column('flow_type', sa.String(length=20), server_default='undefined', nullable=False))
    op.create_index(op.f('ix_transactions_flow_type'), 'transactions', ['flow_type'], unique=False)
    
    # Add CHECK constraint for flow_type
    op.create_check_constraint(
        'valid_flow_type',
        'transactions',
        "flow_type IN ('expense','income','transfer','investment','neutral','undefined')"
    )
    
    # Backfill flow_type based on category for confirmed transactions
    op.execute(
        """
        UPDATE transactions t
        SET flow_type = COALESCE(c.flow_type, 'undefined')
        FROM categories c
        WHERE t.category_id = c.id AND t.confirmed = true
        """
    )
    
    # Set undefined for unconfirmed transactions
    op.execute("UPDATE transactions SET flow_type = 'undefined' WHERE confirmed = false OR category_id IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('valid_flow_type', 'transactions', type_='check')
    op.drop_index(op.f('ix_transactions_flow_type'), table_name='transactions')
    op.drop_column('transactions', 'flow_type')
    op.drop_column('transactions', 'realized_profit')
    op.drop_column('transactions', 'tax')
    op.drop_column('transactions', 'fee')
    op.drop_column('transactions', 'price')
    # ### end Alembic commands ###
